/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PizzaGUI;

/**
 *
 * @author aamir7110
 */
public class PutridPizzaGUI extends javax.swing.JFrame {

    /**
     * Creates new form PutridPizzaGUI
     */
    public PutridPizzaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PutridTitle = new javax.swing.JLabel();
        DiameterLabel = new javax.swing.JLabel();
        DiameterTextfield = new javax.swing.JTextField();
        SubtotalLabel = new javax.swing.JLabel();
        TaxLabel = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        FlavourText = new javax.swing.JLabel();
        CalculateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 63, 75));

        PutridTitle.setBackground(new java.awt.Color(255, 255, 255));
        PutridTitle.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        PutridTitle.setForeground(new java.awt.Color(255, 255, 255));
        PutridTitle.setText("Putrid Pizza");

        DiameterLabel.setFont(new java.awt.Font("Impact", 3, 11)); // NOI18N
        DiameterLabel.setText("Enter The Diameter Of The Pizza");

        DiameterTextfield.setText(" ");

        SubtotalLabel.setFont(new java.awt.Font("Impact", 0, 11)); // NOI18N
        SubtotalLabel.setText("Subtotal:");

        TaxLabel.setFont(new java.awt.Font("Impact", 0, 11)); // NOI18N
        TaxLabel.setText("Tax:");

        Total.setFont(new java.awt.Font("Impact", 0, 11)); // NOI18N
        Total.setText("Total:");

        CalculateButton.setFont(new java.awt.Font("Impact", 1, 11)); // NOI18N
        CalculateButton.setText("Calculate");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CalculateButton)
                .addGap(151, 151, 151))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DiameterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DiameterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(PutridTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SubtotalLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TaxLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Total))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FlavourText, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PutridTitle)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiameterLabel)
                    .addComponent(DiameterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(CalculateButton)
                .addGap(16, 16, 16)
                .addComponent(SubtotalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TaxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FlavourText, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        // TODO add your handling code here:
        //variable declaration
        double diameter,subtotal,total,taxes;
        
        final double TAX = 0.13;
        final double LABOUR = 0.75;
        final double RENT = 0.99;
        
        diameter = Double.parseDouble(DiameterTextfield.getText());
        //rounding numbers and setting text
        subtotal = diameter*0.50+LABOUR+RENT;
        
        subtotal = subtotal*100;
        subtotal = Math.round(subtotal);
        subtotal = subtotal/100;
       
        SubtotalLabel.setText("SubTotal:$"+subtotal);
        
        taxes = subtotal*TAX;
        
        taxes = taxes*100;
        taxes = Math.round(taxes);
        taxes = taxes/100;
        
        TaxLabel.setText("Tax:$"+taxes);
        
        total = subtotal+taxes;
        
        total = total*100;
        total = Math.round(total);
        total = total/100;
        
        Total.setText("Total:$"+total);
        //if statments
        if(diameter <=15){
            
            FlavourText.setText("We Are Going To Make You A Cute little Pizza!");
        }
        else if((diameter<20)||(diameter<40)){
        
            FlavourText.setText("This Will Be Delicious!");
    } 
        else if(diameter>40){
        
            FlavourText.setText("Woah, big pizza! You might need a truck to get this home!");
    }
        
    }//GEN-LAST:event_CalculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PutridPizzaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PutridPizzaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PutridPizzaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PutridPizzaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PutridPizzaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private javax.swing.JLabel DiameterLabel;
    private javax.swing.JTextField DiameterTextfield;
    private javax.swing.JLabel FlavourText;
    private javax.swing.JLabel PutridTitle;
    private javax.swing.JLabel SubtotalLabel;
    private javax.swing.JLabel TaxLabel;
    private javax.swing.JLabel Total;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
